### ISSUE TITLE
Build error on master (missing file or dependency?)

### ISSUE THREAD

**Issue by sztomi** [ja3067/Coral#11]
Trying to build the project on master, I get the following error:

```
➜ make
ocamlbuild -tag bin_annot -I src  -use-ocamlfind -lib unix  -clean
Finished, 0 targets (0 cached) in 00:00:00.
00:00:00 0    (0   ) STARTING                                                                                                                                                                             -------- |rm -f a.out main *.ll *.s *.out *.log *.diff coral
ocamlbuild -tag bin_annot -I src  -use-ocamlfind -lib unix  coral.native
+ ocamlfind ocamlc -c -bin-annot -w -8-26-11 -package llvm -package llvm.analysis -I src -o src/codegen.cmo src/codegen.ml
File "src/codegen.ml", line 1296, characters 50-63:
Error: Unbound module Seq
Command exited with code 2.
Compilation unsuccessful after building 17 targets (0 cached) in 00:00:00.
Makefile:13: recipe for target 'native' failed
make: *** [native] Error 10
```

I need to educate myself in ocaml to know what exactly that means, but it's an error anyway :)

**Comment by ja3067** [comment]
I’ll respond to this more fully tonight, but that’s an issue if you are running an older version of OCaml before 4.07. If you installed ocaml using utop, try running utop switch create 4.07.1. I want to remove this dependency so this isn’t an issue in the future.

**Comment by ja3067** [comment]
FYI I've updated the README.txt with more detailed build instructions and started a dev-readme.txt in the docs folder which explains/will explain the implementation and build system.

**Comment by sztomi** [comment]
Thanks! I definitely just installed whatever debian package I thought I needed. I'll give a spin to utop. In the meantime, I'll close this since I got the solution.

**Comment by ja3067** [comment]
I just removed the one reference to the Seq module which probably made that fail. Can you try cloning the repo again and see if you still get an error? Also, what version of OCaml is downloaded by default on Debian?

**Comment by sztomi** [comment]
I got 4.05 installed from apt. I got the following error when trying to build master with that:

```
ocamlbuild -tag bin_annot -I src  -use-ocamlfind -lib unix  -clean
Finished, 0 targets (0 cached) in 00:00:00.
00:00:00 0    (0   ) STARTING                                                                                                                                                                             -------- |rm -f a.out main *.ll *.s *.out *.log *.diff coral
ocamlbuild -tag bin_annot -I src  -use-ocamlfind -lib unix  coral.native
+ ocamlfind ocamlc -c -bin-annot -w -8-26-11 -package llvm -package llvm.analysis -I src -o src/codegenutils.cmo src/codegenutils.ml
File "src/codegenutils.ml", line 17, characters 16-25:
Error: Unbound value List.init
Command exited with code 2.
Compilation unsuccessful after building 12 targets (0 cached) in 00:00:00.
Makefile:14: recipe for target 'native' failed
make: *** [native] Error 10
```

**Comment by sztomi** [comment]
With 4.07.1:

```
➜ make             
ocamlbuild -tag bin_annot -I src  -use-ocamlfind -lib unix  -clean
Finished, 0 targets (0 cached) in 00:00:00.
00:00:00 0    (0   ) STARTING                                                                                                                                                                             -------- |rm -f a.out main *.ll *.s *.out *.log *.diff coral
ocamlbuild -tag bin_annot -I src  -use-ocamlfind -lib unix  coral.native
+ ocamlfind ocamlc -c -bin-annot -w -8-26-11 -package llvm -package llvm.analysis -I src -o src/coral.cmo src/coral.ml
File "src/coral.ml", line 373, characters 109-115:
Warning 21: this statement never returns (or has an unsound type.)
+ ocamlfind ocamlopt -c -bin-annot -w -8-26-11 -package llvm -package llvm.analysis -I src -o src/coral.cmx src/coral.ml
File "src/coral.ml", line 373, characters 109-115:
Warning 21: this statement never returns (or has an unsound type.)
Finished, 31 targets (0 cached) in 00:00:02.
mv coral.native coral 
./coral test.cl
FileNotFoundError: unable to open file test.cl
```

**Comment by ja3067** [comment]
Just fixed the last issue. This was just a small Makefile error introduced by a recent change. Everything should compile with 4.07.1.

**Comment by sztomi** [comment]
It worked! Thank you. FWIW about the version numbers, they seem to be documented here: https://ocaml.org/docs/install.html

**Comment by ja3067** [comment]
I also just removed the List.init call all together (which was added in 4.05.*), so it should now actually work with the 4.05 version. We've partly added the development guide in docs/dev-readme.md, but we'll finish it up soon. Thanks.
